config/routes.rb
Sppay::Application.routes.draw do
  root "queries#index"
  post "queries/create"
  get "queries/:id" => "queries#show", as: :query
end

app/models/query.rb
class Query < ActiveRecord::Base
  validates :uid, :pub0, presence: true
  validates :page, numericality: { only_integer: true, greater_than: 0 }, allow_nil: true

  after_save :get_response

  private

  def get_response
    if response = Api::SpPay.new(uid, pub0, page).get_data
      write_to_cache(id, Response.new(response))
    end
  end

  def write_to_cache key, value
    Rails.cache.write(key, value, namespace: :sppay, expires_in: 1.hour)
  end
end

app/models/response.rb
class Response
  attr_accessor :count, :offers, :response

  def initialize(json)
    self.response = JSON.parse(json) 
    self.count = @response["count"].to_i
    self.offers = @response["offers"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  respond_to :html
  def index
  end

  def create
    @query = Query.new(query_params)
    if @query.save 
      respond_with @query
    else
      flash[:alert] = @query.errors.full_messages.join('. ')
      redirect_to root_path
    end
  end

  def show
    query = Query.find_by_id params[:id]
    if query && response = read_from_cache(query.id)
      @response = ResponseDecorator.new(response)
      respond_with @response
    else
      flash[:alert] = "No valid response, try again"
      redirect_to root_path
    end
  end

  private

  def query_params
    params.require(:query).permit(:page, :uid, :pub0)
  end

  def read_from_cache key
    Rails.cache.read(key, namespace: :sppay)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Sppay"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#{root_path}") Sppay
          .container.nav-collapse
            %ul.nav


    .container-fluid

      .row-fluid
        .span12
          = bootstrap_flash
          = yield
    
      %footer
        %p Arkadiusz Kusy

app/views/queries/_no_offers.html.haml
.no_offers No offers

app/views/queries/_offers.html.haml
.offer
  - offers.each do |o|
    .title= "Title: #{o["title"]}"
    .payout= "Offer Payout: #{o["payout"]}"
    .thumbnail 
      Offer thumbnail
      %br= image_tag(o["thumbnail"]["lowres"])

app/views/queries/index.html.haml
= simple_form_for Query.new, url: queries_create_path , :html => { :class => 'form-horizontal' } do |f|
  = f.input :uid
  = f.input :pub0
  = f.input :page
  .form-actions
    = f.button :submit, :class => 'btn-primary'
%hr

app/views/queries/show.html.haml
.page-header
  %h1 Response

-if @response.present?
  = @response.offers



.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), root_path, :class => 'btn'